swagger: '2.0'
info:
  title: services
  version: '0.1'
consumes:
  - application/json
  - multipart/form-data
  - application/x-www-form-urlencoded
produces:
  - application/json
paths:
  /api/test:
    post:
      tags:
        - test
      summary: test
      operationId: handlers.api.test
      parameters:
        - name: name
          type: string
          in: formData
      responses:
        '200':
          description: hello word
          schema:
            type: string
  /api:
    get:
      tags:
        - api
      summary: api
      operationId: handlers.api.api
      responses:
        '200':
          description: 接口返回的内容
          schema:
            type: object